# Restore old style debuginfo creation for rpm >= 4.14.
%undefine _debugsource_packages
%undefine _debuginfo_subpackages

# -*- rpm-spec -*-
BuildRoot:      %_topdir/hello_world-0.1.1-Linux
Summary:        hello_world built using CMake
Name:           hello_world
Version:        0.1.1
Release:        1
License:        unknown
Group:          unknown
Vendor:         MyCompany















Prefix: /usr





%define _rpmdir %_topdir/RPMS
%define _srcrpmdir %_topdir/SRPMS
%define _rpmfilename hello_world-0.1.1-Linux.rpm
%define _unpackaged_files_terminate_build 0




%description
DESCRIPTION
===========

This is an installer created using CPack (https://cmake.org). No additional installation instructions provided.



# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT %_topdir/tmpBBroot

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv %_topdir/tmpBBroot $RPM_BUILD_ROOT



%clean

%post



%posttrans


%postun


%pre


%pretrans


%preun


%files
%defattr(-,root,root,-)
"/usr/bin/hello_world"




%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 0.1.1-1
  Generated by CPack RPM (no Changelog file were provided)


